// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgqQnNoqkFy3nSsS_szWoD0R-WqmrcsPg',
    appId: '1:982317055542:web:963f7094d4391e7e6ca297',
    messagingSenderId: '982317055542',
    projectId: 'finance-45d22',
    authDomain: 'finance-45d22.firebaseapp.com',
    storageBucket: 'finance-45d22.firebasestorage.app',
    measurementId: 'G-HQMEV05LDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbcSHNFAbdOp5voOwCA8gMob1TQAyTyBc',
    appId: '1:982317055542:android:03b32f2959fba3c76ca297',
    messagingSenderId: '982317055542',
    projectId: 'finance-45d22',
    storageBucket: 'finance-45d22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF0G8E7uJ67-3dtu286WidP5stUh9g6U4',
    appId: '1:982317055542:ios:1678536446fb651a6ca297',
    messagingSenderId: '982317055542',
    projectId: 'finance-45d22',
    storageBucket: 'finance-45d22.firebasestorage.app',
    iosBundleId: 'com.example.managment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF0G8E7uJ67-3dtu286WidP5stUh9g6U4',
    appId: '1:982317055542:ios:1678536446fb651a6ca297',
    messagingSenderId: '982317055542',
    projectId: 'finance-45d22',
    storageBucket: 'finance-45d22.firebasestorage.app',
    iosBundleId: 'com.example.managment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgqQnNoqkFy3nSsS_szWoD0R-WqmrcsPg',
    appId: '1:982317055542:web:020b5a96322dd8366ca297',
    messagingSenderId: '982317055542',
    projectId: 'finance-45d22',
    authDomain: 'finance-45d22.firebaseapp.com',
    storageBucket: 'finance-45d22.firebasestorage.app',
    measurementId: 'G-M394WPRMMQ',
  );
}
